const express = require('express');
const PORT = process.env.PORT || 3001;
const server = express();
const axios = require('axios');
server.use(express.json());
server.use(express.urlencoded({
    extended: true
}));


server.get('/', async (req, res) => {
  res.send(`Hi! Node.js version: ${process.version}`)
})

server.post('/', async (req, res) => {
     const response = {
        status: '200',
        statusDescription: 'OK',
        headers: {
        },
        body: 'Example body generated by apprunner.',
    };


  res.json(response)
})

server.listen(PORT, () => {
    console.log(`Server listening on http://localhost:${PORT}`);
});
